title: Arend Peter's Game Maker Guide
remote_theme: pmarsceill/just-the-docs

search_enabled: true
search:
    previews: 1
    preview_words_before: 2
    preview_words_after: 2

logo: "/images/logo.png"

color_scheme: custom

aux_links:
  "Video version on Udemy":
    - "//udemy.com"
