title: Game Maker Basics
remote_theme: pmarsceill/just-the-docs

logo: "/assets/images/just-the-docs.png"

color_scheme: custom

aux_links:
  "Video version on Udemy":
    - "//udemy.com"
  "More Arend Peter Courses":
    - "//arendpeter.com"

