title: Arend Peter's Game Maker Guide
remote_theme: pmarsceill/just-the-docs

search_enabled: true
search:
    previews: 1
    preview_words_before: 2
    preview_words_after: 2

logo: "/images/logo.png"

color_scheme: custom

aux_links:
    "Video version on<br><img style='width:50%;' src='https://www.udemy.com/staticx/udemy/images/v7/logo-udemy.svg'/>":
    - "//udemy.com"

footer_content:
    "This site uses <a href='https://github.com/pmarsceill/just-the-docs'>Just the Docs</a>, a documentation theme for Jekyll."
