title: Arend Peter's Game Maker Guide
remote_theme: pmarsceill/just-the-docs

logo: "/assets/images/logo.png"

color_scheme: custom

aux_links:
  "Video version on Udemy":
    - "//udemy.com"
  "More Arend Peter Courses":
    - "//arendpeter.com"
